# Generated by Django 3.2.17 on 2023-03-05 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20230304_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
