# Generated by Django 3.2.17 on 2023-03-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_remove_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default=None, upload_to='images')),
                ('description', models.TextField(blank=True)),
                ('homePage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
