# Generated by Django 3.2.17 on 2023-03-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_heroimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeroImages',
            new_name='HeroImage',
        ),
    ]
