# Generated by Django 3.2.17 on 2023-03-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_rename_heroimages_heroimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(default=None, upload_to='images')),
                ('event_ongoing', models.BooleanField(default=False)),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
                ('event_address', models.CharField(max_length=200)),
                ('event_city', models.CharField(max_length=30)),
                ('event_state', models.CharField(max_length=20)),
                ('event_zip', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
