# Generated by Django 3.2.17 on 2023-03-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0010_alter_event_event_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_ongoing',
            new_name='ongoing_event',
        ),
    ]
