# Generated by Django 3.2.17 on 2023-03-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0011_rename_event_ongoing_event_ongoing_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='forSale',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
