# Generated by Django 3.2.17 on 2023-03-19 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0012_auto_20230318_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='forSale',
            new_name='for_sale',
        ),
    ]
