# Generated by Django 3.2.17 on 2023-03-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0013_rename_forsale_image_for_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='sold',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
