# Generated by Django 3.2.18 on 2023-04-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0014_auto_20230318_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='media',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='featured',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='for_sale',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='sold',
            field=models.BooleanField(blank=True),
        ),
    ]
