# Generated by Django 3.2.18 on 2023-04-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0015_auto_20230401_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='media',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
