# Generated by Django 3.2.18 on 2023-04-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0016_alter_image_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='home_page',
            field=models.BooleanField(default=False),
        ),
    ]
